export const AppActionsTypes ={
    FETCH_USER_LOADING:"FETCH_USER_LOADING",
    FETCH_USER_SUCCESS:"FETCH_USER_SUCCESS",
    FETCH_USER_FAILURE:"FETCH_USER_FAILURE",
    ADD_USER_SUCCESS:"ADD_USER_SUCCESS",
    ADD_USER_FAILURE:"ADD_USER_FAILURE"
}